apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1 # Podレプリカ数
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers: # Podに含めるコンテナのリスト
      - image: docker.io/nginx:latest
        name: myapp
        env:
        - name: MY_ENV
          value: World!!
        volumeMounts:
        - name: myapp-config
          mountPath: /etc/nginx/templates
      volumes:
      - name: myapp-config
        configMap:
          name: myapp-config
